CREATE TABLE Users (
ID INT IDENTITY PRIMARY KEY,
NOME VARCHAR(70) NOT NULL,
CPF CHAR (11) UNIQUE NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
SENHA VARCHAR (50) NOT NULL,
DATA_CADASTRO DATE DEFAULT GETDATE() NOT NULL,
PROMO_BONUS BIT DEFAULT 1 NULL,
ATIVO BIT DEFAULT 1,
)
CREATE TABLE Wallets(
CONTAID INT PRIMARY KEY CONSTRAINT fk_User_Wallet
         FOREIGN KEY REFERENCES Users(ID) NOT NULL,
SALDO DECIMAL(13,2) DEFAULT '0.00' NOT NULL,
NUMEROCONTA INT UNIQUE NOT NULL,
DATA_CRIACAO DATE DEFAULT GETDATE() NOT NULL,
)
CREATE TABLE Transferences(
ID INT IDENTITY PRIMARY KEY,
CONTA_UM INT CONSTRAINT fk_Wallet_Transaction_one
         FOREIGN KEY REFERENCES Wallets(CONTAID) NOT NULL,
CONTA_DOIS INT CONSTRAINT fk_Wallet_Transaction_two
         FOREIGN KEY REFERENCES Wallets(CONTAID) NOT NULL,
DATA_TRANSACAO DATE DEFAULT GETDATE() NOT NULL,
VALOR DECIMAL(13,2) NOT NULL,
)
CREATE TABLE CashMovements(
ID INT IDENTITY PRIMARY KEY,
SALDO_MOVIMENTO DECIMAL(13,2)  NOT NULL,
ENTRADA_VALOR FLOAT NULL,
SAIDA_VALOR DECIMAL(13,2)  NULL,
SALDO_NOVO DECIMAL(13,2)  NOT NULL,
DATA_OPERACAO DATE DEFAULT GETDATE() NOT NULL,
)


